### ISSUE TITLE
Use MonadError/Either instead of error in merge

### ISSUE THREAD

**Issue by tirumaraiselvan** [tirumaraiselvan/graphql-engine#26]
https://github.com/tirumaraiselvan/graphql-engine/blob/5f56eb7a3ed0dd983e54c2bef2f2d55dd8535567/server/src-lib/Hasura/GraphQL/Execute.hs#L450

**Comment by jberryman** [comment]
I can take this

**Comment by jberryman** [comment]
I can take this one.
