### ISSUE TITLE
Remote joins: remove `hasura_fields` from `create_remote_relationship`

### ISSUE THREAD

**Issue by jberryman** [tirumaraiselvan/graphql-engine#64]
Instead we can make this implicit and extract referenced fields from the `remote_field` section. Simplifies API and removes something extra to validate.

This also removes the weird question of whether including extraneous hasura fields that go unused should be a validation error.

**Comment by tirumaraiselvan** [comment]
Closed via https://github.com/hasura/graphql-engine/commit/2d9b32336f6f04ada803814f95d039ebc5ec4088
